<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TEMPO.Contracts\TEMPO.Contracts.csproj" />
    <ProjectReference Include="..\TEMPO.Data\TEMPO.Data.csproj" />
    <ProjectReference Include="..\TEMPO.Service\TEMPO.Service.csproj" />
  </ItemGroup>

</Project>
